### Numpy
- 데이터는 행렬로 표현
- 행렬 데이터로 빠르게 계산
- 행렬 데이터 생성, 수정, 계산 등을 빠르게 처리해주는 패키지
- 특징
    - C, C++, 포트란으로 작성 (파이썬이 인터프리터이지만 내부적으로 빠르게 계산되는 이유)
    - 선형대수학을 빠르게 연산 
        - 스칼라, 벡터, 매트릭스

In [36]:
import numpy as np

In [37]:
# 행렬 데이터 생성
# ndarray : 한가지 데이터 타입만 값으로 사용이 가능

In [38]:
array = np.array([1,2,3])
type(array), array

(numpy.ndarray, array([1, 2, 3]))

In [3]:
array2 = np.array(
    [[1,2,3],
     [4,5,6]],

)

array2, array2.ndim, array2.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 (2, 3))

In [40]:
# 행력의 모양(shape) 변경하기 
array2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
array2.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [42]:
array2.reshape(3,2,1)

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [43]:
# 행렬 데이터의 선택 : offset index: masking

In [2]:
array2[1][:2]

array([4, 5])

In [3]:
 array2[1,2] # = array2[1][2] 

6

In [46]:
# 데이터 수정

In [47]:
ls = [1,2,3]
ls[1] = 5
ls


[1, 5, 3]

In [4]:
array2[1,2] = 10
array2

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [5]:
# 브로드캐스팅
array2[0] = 0
array2

array([[ 0,  0,  0],
       [ 4,  5, 10]])

In [6]:
array2[0] = [7,8,9] # 0행의 숫자 치환
array2

array([[ 7,  8,  9],
       [ 4,  5, 10]])

In [51]:
# 조건으로 선택

idx = array2 > 7
idx

array([[False,  True,  True],
       [False, False,  True]])

In [52]:
array2[idx]

array([ 8,  9, 10])

In [53]:
array2[idx] = 100
array2

array([[  7, 100, 100],
       [  4,   5, 100]])

In [54]:
# 행렬 데이터의 생성 2

In [10]:
data = np.zeros((2,3))
data

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
data.dtype

dtype('float64')

In [20]:
data2 = data.astype("int")
data2

array([[0, 0, 0],
       [0, 0, 0]])

In [60]:
data = np.ones((2,3,2))
data

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [65]:
# arange (range 문법과 동일, array 타입으로 출력)
np.arange(5)

array([0, 1, 2, 3, 4])

In [63]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [64]:
np.arange(5, 10, 2)

array([5, 7, 9])