### summary
- numpy: 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성1: ndarray, ap.array(iterable)
- 행렬의 생성2: ones, zeros
- 행렬의 데이터 선택: array[x, y,z]
- 행렬 데이터 수정
    - 행렬 데이터를 선택
    - =, > (scala, vector, matrix)
    - broadcasting 브로드캐스팅 개념
- arange: list에서 사용하는 range: 결과가 ndarray

### quiz 
- 100~130 까지 랜덤함 순자를 가지는 8*8 행렬을 만들고 
- 3의 배수는 fizz, 5의 배수는 buzz, 3과 5의 배수는 fizzbuzz로 변환

```
datas = np.random.randint(100,130, size = (8,8))
```

- 데이터 타입이 정수 -> 문자열 : ndarray.astype

In [13]:
# 100~130 까지 랜덤함 순자를 가지는 8*8 행렬을 만들고

matrix = np.random.randint(100, 131, 8*8)

In [14]:
idx_3 = matrix % 3 == 0
idx_5 = matrix % 5 == 0
idx_15 = matrix % 15 == 0

In [15]:
idx_3

array([False, False, False, False,  True,  True, False, False, False,
       False,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True, False,  True, False,  True, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False,  True,  True,  True,  True, False, False,  True, False,
       False])

In [16]:
result = matrix.astype("str")

In [17]:

result[idx_3] = "fiz"
result[idx_5] = "buz"
result[idx_15] = "fizbuz"
result

array(['buz', 'buz', 'buz', 'buz', 'fiz', 'fiz', '121', 'buz', 'buz',
       '122', 'fizbuz', 'fizbuz', '121', 'fiz', 'buz', 'fiz', 'fiz',
       '128', '104', 'fiz', 'fizbuz', 'fiz', 'fizbuz', 'fizbuz', 'fiz',
       'buz', '116', '109', 'fiz', '106', 'fizbuz', '119', 'fiz', '103',
       'buz', '103', '107', 'fiz', '127', '101', '113', 'buz', 'buz',
       '128', '119', '101', '101', '107', 'fiz', '104', '119', 'buz',
       '128', 'buz', '112', 'fiz', 'fiz', 'fiz', 'fiz', '121', '119',
       'fizbuz', '109', '127'], dtype='<U21')

In [36]:
import numpy as np

In [37]:
datas = np.random.randint(100, 130, size=(8, 8))

In [38]:
datas

array([[107, 112, 128, 103, 117, 111, 124, 102],
       [116, 116, 125, 129, 123, 106, 129, 101],
       [116, 103, 124, 108, 117, 127, 127, 122],
       [124, 113, 110, 110, 100, 104, 114, 116],
       [102, 111, 109, 109, 127, 113, 108, 119],
       [127, 109, 113, 107, 121, 100, 120, 111],
       [102, 120, 104, 124, 119, 119, 125, 116],
       [119, 109, 115, 124, 127, 108, 121, 117]])

In [39]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T, F matrix 생성
idx_3 = datas % 3 == 0
idx_5 = datas % 5 == 0
idx_15 = datas % 15 == 0

In [40]:
# 데이터 타입으로 str 으로 변환
datas.dtype
result = datas.astype("str")
result

array([['107', '112', '128', '103', '117', '111', '124', '102'],
       ['116', '116', '125', '129', '123', '106', '129', '101'],
       ['116', '103', '124', '108', '117', '127', '127', '122'],
       ['124', '113', '110', '110', '100', '104', '114', '116'],
       ['102', '111', '109', '109', '127', '113', '108', '119'],
       ['127', '109', '113', '107', '121', '100', '120', '111'],
       ['102', '120', '104', '124', '119', '119', '125', '116'],
       ['119', '109', '115', '124', '127', '108', '121', '117']],
      dtype='<U21')

In [41]:
# T, F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입

In [42]:
result[idx_3] = " fiz"
result[idx_5] = "buz"
result[idx_15] = "fizbuz"

In [33]:
result

array([['fiz', 'fiz', 'fiz', '127', '114', '127', '107', 'fiz'],
       ['114', '102', 'fiz', 'fiz11', '123', '128', '128', '121'],
       ['fiz', '129', 'fiz', 'fiz', '118', '115', '115', '113'],
       ['fiz', 'fiz', '105', '117', '108', 'fiz', '110', 'fiz'],
       ['116', '101', '121', '114', '125', '127', '115', '123'],
       ['122', 'fiz', '112', '118', '100', '111', '127', 'fiz'],
       ['103', '107', '129', '111', 'fiz11', '104', 'fiz', '125'],
       ['fiz', '120', '126', '105', '114', 'fiz', 'fiz', 'fiz']],
      dtype='<U21')

### Quiz
- 1~20까지 랜덤한 숫자를 가지는 5*5 행렬 생성 
- 최대값에는 Max, 최소값에는 Min 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수 

```
np.min(ndarray)
np.max(ndarray)
```

In [18]:
array = np.random.randint(1, 21, (5, 5))

In [19]:
array

array([[ 1,  7, 15, 14, 17],
       [ 7, 14,  7, 15,  5],
       [ 3,  2,  2, 15, 13],
       [18, 15,  3,  3, 18],
       [17,  5, 17, 16, 13]])

In [20]:
idx_min, idx_max = np.min(array), np.max(array)
idx_min, idx_max

(1, 18)

In [21]:
idx_min = array == np.min(array)
idx_max = array == np.max(array)

In [22]:
result = array.astype("str")
result[idx_min] = "min"
result[idx_max] = "max"

In [23]:
result

array([['min', '7', '15', '14', '17'],
       ['7', '14', '7', '15', '5'],
       ['3', '2', '2', '15', '13'],
       ['max', '15', '3', '3', 'max'],
       ['17', '5', '17', '16', '13']], dtype='<U21')

### 1. linspace, logsplace 함수
- linspace : 설정한 범위에서 선형적으로 분한할 위치의 값을 출력
- logspace : 설정한 범위에서 로그한 분할한 위치의 값을 출력

In [20]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [21]:
# logspace
# log10(x1) = 2, log10(x2) = 3, log10(x3) = 4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [22]:
# 30세에 연봉이 $10000이고, 60세의 연봉이 $1000000 일때
# 연봉이 선형으로 증가 vs.지수함수로 증가하는 두 경우에서 40세, 50세의 연봉을 출력

In [25]:
age_30 = 100000
age_60 = 1000000

In [26]:
np.linspace(age_30, age_60, 5)

array([ 100000.,  325000.,  550000.,  775000., 1000000.])

In [27]:
np.logspace(np.log10(age_30), np.log10(age_60), 5)

array([ 100000.        ,  177827.94100389,  316227.76601684,
        562341.32519035, 1000000.        ])

### 2. numpy random
- seed: 랜덤값의 설정값
- rand: 균등분포로 난수를 발생 (뽑힐 확률이 균등)
- randn: 정규분포로 난수를 발생 (뽑힐확 률이 정규분포를 따름)
- randint: 균등분포로 정수값을 발생
- shuffle: 행렬 데이터를 섞어줌
- choice: 특정확률로 데이터를 선택

In [31]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(3)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([34, 13, 66, 82, 10, 31, 29, 84, 51, 20]))

In [32]:
np.random.rand(10)

array([0.2478883 , 0.0935515 , 0.69482365, 0.14537014, 0.4531723 ,
       0.21557701, 0.35390507, 0.49263593, 0.91330145, 0.76582638])

In [34]:
np.random.randn(10)

array([ 0.31640691,  0.56939549,  1.01924992, -0.57636719, -1.40340536,
       -1.88259849,  1.36976982, -0.41159769,  0.62652349, -1.83887166])

In [68]:
# shuffle

r = np.random.randint(1, 10, (3, 4))
r

array([[6, 8, 4, 7],
       [8, 8, 5, 6],
       [8, 8, 8, 5]])

In [55]:
a = r.reshape(12)
np.random.shuffle(a)

a.reshape(3,4)

# 가장 바깥 차원에서만 바뀌므로, 함수를 1차원으로 reshape 한 후 shuffle 한 후 다시 원래 차수로 변경해주면 전체 shuffle 가능

array([[5, 5, 6, 4],
       [3, 8, 7, 6],
       [5, 8, 8, 6]])

In [60]:
# choice
np.random.choice(5, 10, p=[0.2, 0.2, 0.2, 0.2, 0.2])

array([1, 4, 0, 0, 2, 4, 2, 4, 0, 3])

In [69]:
# unique
numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)


[4 5 6 7 8]
[1 2 2 1 6]


### 3. 행렬데이터의 결합 
- concatenate

In [5]:
na1 = np.random.randint(10, size=(1,2))
na2 = np.random.randint(10, size=(1, 2))
na3 = np.random.randint(10, size=(3, 3))

In [6]:
na1

array([[1, 0]])

In [7]:
na2

array([[4, 4]])

In [75]:
na3

array([[3, 5, 8],
       [5, 7, 8],
       [9, 2, 1]])

In [66]:
# 세로결합

In [8]:
np.concatenate((na1, na2))

array([[1, 0],
       [4, 4]])

In [68]:
# 가로결합

In [69]:
np.concatenate((na2, na3), axis=1)

array([[8, 4, 6, 7, 0],
       [1, 4, 7, 8, 1],
       [0, 5, 5, 3, 6]])

In [71]:
# c_, r_
np.c_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [72]:
np.r_[np.array([1, 2, 3]), np.array([4, 5, 6])]

array([1, 2, 3, 4, 5, 6])

In [73]:
# split, car, std, mean ...