### 선형회귀분석
- 프리미어리그 데이터(득점, 실점, 승점)
- 득점, 실점 -> 승점 예측하는 모델
- scikit-learn 패키지
    - 데이터 마이닝 및 데이터 분석 모델을 위한 도구
    - 상업적으로 사용이 가능한 오픈소스


In [3]:
import pickle
# 선형회귀모델 
from sklearn import linear_model
# 학습 데이터와 테스트 데이터를 나눠주는 모듈
from sklearn.model_selection import train_test_split
# 모델을 평가해주는 모듈
from sklearn.metrics import mean_absolute_error

### 분석절차
- 데이터 로드
- 데이터 전처리: 
    - 독립변수와 종속변수를 나눠줌
    - 학습데이터와 테스트데이터를 나눠줌
- 데이터 분석: 선형회귀 모델 작성
- 성능평가: MAE
- 예측 코드 작성

In [5]:
# 1. 데이터 로드
p_df = pd.read_csv("datas/premierleague.csv")
p_df.tail(1)

name  gf  ga  points
19  West Bromwich Albion  31  56      31

In [11]:
# 2. 데이터 전처리
# 2-1. 독립변수, 종속변수 나누기
df_x = p_df[["gf", "ga"]]
df_y = p_df[["points"]]

In [24]:
# 2-2. 학습데이터, 테스트데이터 나누기
train_x,test_x,train_y,test_y = train_test_split(df_x, df_y, test_size=0.3, random_state=1)

In [25]:
# 3. 데이터 분석 : 선형회기 모델
model = linear_model.LinearRegression()

In [26]:
model.fit(train_x, train_y)

LinearRegression()

In [27]:
# 4. 성능평가 : MAE

In [28]:
pred_y = model.predict(test_x)
pred_y

array([[80.88065736],
       [40.79778662],
       [50.9467527 ],
       [46.31419247],
       [76.04209484],
       [40.23228639]])

In [30]:
test_y["points"].values

array([75, 36, 54, 44, 77, 40])

In [31]:
pred_y = np.around(pred_y.flatten()).astype("int")
pred_y

array([81, 41, 51, 46, 76, 40])

In [33]:
mae = mean_absolute_error(test_y, pred_y)
round(mae,2)

2.83

In [36]:
# 5. 예측 함수
def make_df(gf, ga):
    return pd.DataFrame({"gf" :[gf], "ga":[ga]})

In [37]:
gf, ga = 78, 30

In [39]:
result = int(model.predict(make_df(gf, ga)).flatten()[0])
result

82

In [43]:
# pickle 파일로 모델 저장하기
with open("datas/p_model.pkl", "wb") as f:
    pickle.dump(model, f)


In [47]:
with open ("datas/p_model.pkl", "rb") as f:
    load_model = pickle.load(f)

In [48]:
gf, ga = 78, 30
result = int(model.predict(make_df(gf, ga)).flatten()[0])
result

82